version: ""

formatter: markdown table

name: cloudwatch-tf-war-alarms

content: |-
  # cloudwatch-tf-war-alarms

  GitHub: [https://github.com/StratusGrid/cloudwatch-tf-war-alarms)

  This module will create a bunch or rules to cover the security alarms of a Well Architected Review.

  ## Examples

  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```

  ```hcl
  {{ include "examples/example2.tfnot" }}
  ```

  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  Note, manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml`

sections:
  show:
    - requirements
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
